rails/pictweet/config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'
  get 'likes/destroy'
  devise_for :users
  root   'tweets#index'
  resources :tweets do
    resources :comments, only: [:create]
  end
  
  resources :tweets do
    resources :likes, only: [:create, :destroy]
  end
  
  resources :users, only: [:show] 
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # get    'tweets'　        => 'tweets#index'
  # get    'tweets/new'      => 'tweets#new'
  # post   'tweets'          => 'tweets#create'
  # delete 'tweets/:id'      => 'tweets#destroy'
  # get    'tweets/:id/edit' => 'tweets#edit'
  # patch  'tweets/:id'      => 'tweets#update'
  # get    'users/:id'       => 'users#show' #マイページ
  # get    'tweets/:id'      => 'tweets#show'

rails/pictweet/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/pictweet/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

rails/pictweet/app/models/leki.rb
class Leki < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

rails/pictweet/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet, counter_cache: :likes_count
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

rails/pictweet/app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  
  has_many :comments
  # has_many   :likes, dependent: :destroy
  # has_many :liked_users, through: :likes, source: :user

  # def like_user(user_id)
  # likes.find_by(user_id: user_id)
  # end

end

rails/pictweet/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  
  has_many :comments
end

rails/pictweet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery with: :exception
 before_action :configure_permitted_parameters, if: :devise_controller?

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
 end
end

rails/pictweet/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # binding.pry
    @comment = Comment.create(comment_params)
    respond_to do |f|
      f.html { redirect_to tweet_path(params[:tweet_id]) }
      f.json
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

rails/pictweet/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(tweet_id: params[:tweet_id])
    redirect_to root_path
  end

  def destroy
    @like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    @like.destroy
    redirect_to root_path, notice: 'ふぁぼを取り消しました。'
  end
  
  
end

rails/pictweet/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  before_action :move_to_index, except: [:index, :show]
  
  
  def index
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(5) #allメソッドは省略可
  end

  def new

  end

  def create
    Tweet.create(image: tweet_params[:image], text: tweet_params[:text], user_id: current_user.id)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end
  
  def update
    tweet = Tweet.find(params[:id])
   if tweet.user_id == current_user.id
    tweet.update(tweet_params)
   end
  end
  
  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
    @comment = Comment.new
    # @like = Like.new
  end
  
  
  private
  def tweet_params
    params.permit(:image,:text)
  end
  
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

rails/pictweet/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # binding.pry
    @user = User.find(params[:id])
    @nickname = current_user.nickname
    @tweets = @user.tweets.page(params[:page]).per(5).order("created_at DESC")
  end
end

rails/pictweet/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/pictweet/app/helpers/comments_helper.rb
module CommentsHelper
end

rails/pictweet/app/helpers/likes_helper.rb
module LikesHelper
end

rails/pictweet/app/helpers/tweets_helper.rb
module TweetsHelper
end

rails/pictweet/app/helpers/users_helper.rb
module UsersHelper
end

rails/pictweet/app/views/tweets/_index.html.erb
<p>
  <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>:</strong>
          <%= comment.text %>
</p>

rails/pictweet/app/views/tweets/_menu.html.erb
<div class="tab-menu">
  <ul>
    <li id="left" class="selected"><%= link_to "タイムライン", root_path %></li>
    <% if user_signed_in? %>
    <li id="right"> <%= link_to "マイページ", user_path(current_user) %></a></li>
    <% end %>
  </ul>
</div> 

rails/pictweet/app/views/tweets/_tweet.html.erb
    <div class="content_post" style="background-image: url(<%= tweet.image %>);">
        <div class="more">
            <span><%= image_tag 'arrow_top.png' %></span>
            <ul class="more-list">
              <li>
                <%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %>
              </li>
              <% if user_signed_in? && current_user.id == tweet.user_id %>
                <li>
                  <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete, data: { confirm: 'このtweetを削除します。よろしいですか？'} %>
                </li>
                <li>
                  <%= link_to '編集', edit_tweet_path(tweet), method: :get %>
                </li>
              <% end %>
            </ul>
        </div>
        <%= simple_format(tweet.text) %>
      <span class="name">
        <a href="">
          <span>投稿者</span><%= tweet.user.nickname %>
        </a>
        <!--<p class="good">-->
        <!--  いいね！-->
        <!--</p>-->
        <!--<input type="button" value="ボタン">-->
        <%#= link_to "#{tweet.liked_users.count}件のいいね", root_path %>

      </span>
    </div>

rails/pictweet/app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
  </div>
</div>

rails/pictweet/app/views/tweets/destroy.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

rails/pictweet/app/views/tweets/edit.html.erb
<div class="contents row">
  <%= form_tag("/tweets/#{@tweet.id}", method: :patch, data: { confirm: 'このtweetの内容を更新します。よろしいですか？'}  ) do %>
    <h3>
      編集する
    </h3>
    <input placeholder="Image Url" type="text" name="image" value="<%= @tweet.image %>" autofocus="true">
    <textarea cols="30" name="text" placeholder="text" rows="10"><%= @tweet.text %></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>  

rails/pictweet/app/views/tweets/index.html.erb
  <div class="contents row">
    <p>投稿一覧</p>
        <% @tweets.each do |tweet| %>
          <%= render partial: "tweet", locals: { tweet:tweet } %>
          <%#= render partial: "common/like", locals: { tweet:tweet, likes: @likes } %>
        <% end %>
        <%= paginate(@tweets) %>
  </div>
  
  

rails/pictweet/app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_tag('/tweets', method: :post) do %>
      <h3>
        投稿する
      </h3>
      <input type="text" name="image" placeholder="Image URL" autofocus="true">
      <textarea name="text" placeholder="text" rows="10" cols="30"></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>
<div>

rails/pictweet/app/views/tweets/show.html.erb
<div class="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
        </li>
      </ul>
      </div>
    <% end %>
      <%= simple_format(@tweet.text) %>
      <span class="name">
        <a href="/users/<%= @tweet.user.id %>">
          <span>投稿者</span><%= @tweet.user.nickname %>
        </a>



        <h3><%#= link_to "#{@tweet.likes.count}件のふぁぼ", root_path %></h3>
        <%# if current_user.already_liked?(@tweet) %>
          <%#= button_to 'ふぁぼを消す', tweet_like_path(@tweet), method: :delete %>
        <%# else %>
          <%#= button_to 'ふぁぼ', tweet_likes_path(@tweet) %>
        <%# end %>
      </span>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
        <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
        <input type="submit" value="SENT">
      <% end %>
      
<%= form_with(model: [@tweet, @comment], local: true, id: "new_comment") do |form| %> 
  <%= form.text_area :text, placeholder: "コメントする" , rows: "2", class: "textbox" %>
  <%= form.submit "SEND", class: "form__submit" %>
      <% end %>
    <% end %>
    
    <div class="comments">
      <h4>👺コメント一覧👺</h4>
      <% if @comments %>
       <%= render partial: 'index', collection: @comments, :as => "comment" %>
        <%# @comments.each do |comment| %>
                     <!--<p>-->
            <!--  <strong><%#= link_to comment.user.nickname, "/users/#{comment.user_id}" %>:</strong>-->
            <!--  <%#= comment.text %>-->
            <!--</p>-->
        <%# end %>      
      <% end %>
    </div>    
  </div>
</div>

rails/pictweet/app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>